#!/usr/bin/env python3
"""
Setup script for shared secrets directory
Creates ~/.proj344_secrets/ and copies your existing secrets there
"""

import os
import shutil
from pathlib import Path

def setup_shared_secrets():
    """Setup shared secrets directory for cross-repo access"""

    print("=" * 80)
    print("PROJ344 SHARED SECRETS SETUP")
    print("=" * 80)
    print()

    # 1. Create shared secrets directory
    shared_dir = Path.home() / '.proj344_secrets'
    print(f"[1/3] Creating shared secrets directory: {shared_dir}")
    shared_dir.mkdir(exist_ok=True)
    print("      [OK] Directory created")
    print()

    # 2. Copy secrets from Streamlit secrets.toml to .env format
    streamlit_secrets = Path('.streamlit') / 'secrets.toml'
    shared_env = shared_dir / '.env'

    print(f"[2/3] Converting Streamlit secrets to .env format")

    if streamlit_secrets.exists():
        print(f"      Reading from: {streamlit_secrets}")

        # Read Streamlit secrets
        secrets = {}
        with open(streamlit_secrets, 'r', encoding='utf-8') as f:
            for line in f:
                line = line.strip()
                if line and not line.startswith('#') and '=' in line:
                    key, value = line.split('=', 1)
                    key = key.strip()
                    value = value.strip().strip('"').strip("'")
                    secrets[key] = value

        # Write to .env format
        with open(shared_env, 'w', encoding='utf-8') as f:
            f.write("# PROJ344 Shared Secrets\n")
            f.write("# Generated from .streamlit/secrets.toml\n")
            f.write("# Auto-generated by setup_shared_secrets.py\n")
            f.write("\n")

            for key, value in secrets.items():
                f.write(f"{key}={value}\n")

        print(f"      [OK] Created: {shared_env}")
        print(f"      [OK] Converted {len(secrets)} secrets")
    else:
        print(f"      [WARN] {streamlit_secrets} not found")
        print(f"      Creating empty template at {shared_env}")

        with open(shared_env, 'w', encoding='utf-8') as f:
            f.write("# PROJ344 Shared Secrets\n")
            f.write("# Add your secrets here in KEY=value format\n\n")
            f.write("SUPABASE_URL=https://your-project.supabase.co\n")
            f.write("SUPABASE_KEY=your_supabase_anon_key\n")
            f.write("OPENAI_API_KEY=sk-proj-your_key_here\n")
            f.write("ANTHROPIC_API_KEY=sk-ant-your_key_here\n")
            f.write("TELEGRAM_BOT_TOKEN=your_token_here\n")

    print()

    # 3. Test the config loader
    print(f"[3/3] Testing config loader")

    try:
        from config_loader import ConfigLoader
        config = ConfigLoader()
        secrets = config.load()

        print(f"      [OK] Config loader working")
        print(f"      [OK] Loaded {len(secrets)} secrets")
        print(f"      Source: {config.get_source()}")
    except Exception as e:
        print(f"      [WARN] Error testing config loader: {e}")

    print()
    print("=" * 80)
    print("SETUP COMPLETE")
    print("=" * 80)
    print()
    print("Your shared secrets are now available at:")
    print(f"  {shared_env}")
    print()
    print("All repos can now access these secrets using:")
    print("  from config_loader import get_secret")
    print("  supabase_url = get_secret('SUPABASE_URL')")
    print()
    print("To use in other repos:")
    print("  1. Copy config_loader.py to the other repo")
    print("  2. Import and use: from config_loader import get_secret")
    print("  3. Secrets will load automatically from shared directory")
    print()

if __name__ == "__main__":
    setup_shared_secrets()
